#ifndef SENSESP_SIGNALK_DELTA_QUEUE_H_
#define SENSESP_SIGNALK_DELTA_QUEUE_H_

#include <ArduinoJson.h>
#include <list>
#include <map>
#include <vector>

namespace sensesp {

/**
 * @brief Signal K delta queue
 *
 * This class implements a Signal K delta queue. There should be a unique queue
 * for each possible output channel (SKWSClient, NMEA 2000 messages,
 * carrier pigeons).
 */
class SKDeltaQueue {
 public:
  SKDeltaQueue(unsigned int max_buffer_size = 20);
  void append(const String& val);
  bool data_available();
  void get_delta(String& output);

  /**
   * @brief Drain the queue into one or more deltas.
   *
   * @param output Receives the deltas, oldest values first.
   * @param max_delta_size Longest delta the transport accepts, in bytes; the
   * batch is split across as many deltas as it takes to stay within it. 0
   * means no limit. A single value longer than this cannot be split and is
   * emitted in a delta of its own.
   */
  void get_deltas(std::vector<String>& output, size_t max_delta_size = 0);

  void connect_emitters();

  /// Used to indicate that the next update generated by this
  /// delta should have metadata added to it.
  void reset_meta_send() {
    take_semaphore();
    this->meta_sent_ = false;
    release_semaphore();
  }

  bool take_semaphore(uint64_t timeout_ms = 0);
  void release_semaphore();

 private:
  unsigned int max_buffer_size;
  std::list<String> buffer{};
  bool meta_sent_;

  std::size_t get_buffer_size() {
    std::size_t size;
    take_semaphore();
    size = buffer.size();
    release_semaphore();
    return size;
  }

  // Builds the deltas for one context's values, splitting on max_delta_size.
  void emit_deltas(const String& context,
                   const std::vector<const String*>& items,
                   size_t max_delta_size, std::vector<String>& output);

  // Builds the one-shot metadata deltas, splitting on max_delta_size.
  void emit_metadata_deltas(size_t max_delta_size, std::vector<String>& output);

  StaticSemaphore_t semaphore_buffer_;
  SemaphoreHandle_t semaphore_ = NULL;
};

}  // namespace sensesp

#endif
